name: cyber_safe
description: "CyberSafe is a password manager that helps you to store your passwords securely. It uses the ObjectBox database to store the passwords and encrypts them using the AES algorithm. The app also supports biometric authentication and dark mode."
publish_to: "none"
version: 1.0.7+8

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.2.0
  cupertino_icons: ^1.0.8
  #security
  crypto: 3.0.3
  encrypt: 5.0.3
  flutter_secure_storage: 9.2.2
  envied: 0.5.4+1
  #database
  objectbox: 4.0.1
  objectbox_flutter_libs: any
  csv: 6.0.0
  #provider
  provider: 6.1.2
  path_provider: ^2.1.3
  path: ^1.9.0
  #utils
  intl: 0.19.0
  get_it: 7.7.0
  local_auth: 2.2.0
  file_picker: 8.0.3
  secure_application: 4.0.1
  pin_code_fields: 8.0.1
  flutter_styled_toast: 2.2.1
  downloadsfolder: 1.1.0
  permission_handler: 11.3.1
  in_app_review: 2.0.9
  share_plus: 9.0.0
  url_launcher: ^6.3.0
  
  #ui
  upgrader: ^10.3.0
  numberpicker: ^2.1.2
  flutter_markdown: ^0.7.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  bootstrap_icons: ^1.11.3
  flutter_native_splash: ^2.4.0
  pie_chart: ^5.4.0
  package_info_plus: ^8.0.0
  password_strength_checker: ^1.2.3
  scrollable_positioned_list: ^0.3.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  envied_generator: ^0.5.3
  objectbox_generator: any
flutter:
  uses-material-design: true
  assets:
    - assets/locales/
    - assets/images/
    - assets/animations/
    - assets/images/icons/
    - assets/images/brand_icons/
    - assets/images/brand_icons/banks/
    - assets/markdown/privacy_policy/
    - assets/markdown/terms_of_service/
