name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter with a specific version
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0' # Hoặc phiên bản cụ thể cần thiết để phù hợp với Dart SDK

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
